apiVersion: v2
name: "cray-hms-sls"
version: 6.0.0
description: "Kubernetes resources for cray-hms-sls"
home: https://github.com/Cray-HPE/hms-sls-charts
sources:
  - https://github.com/Cray-HPE/hms-sls
maintainers:
  - name: rsjostrand-hpe
dependencies:
  - name: cray-service
    version: "~11.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-postgresql
    version: "~1.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
annotations:
  artifacthub.io/license: MIT
appVersion: 2.5.0
