apiVersion: v2
name: "cray-hms-sls"
version: 6.1.1
description: "Kubernetes resources for cray-hms-sls"
home: https://github.com/Cray-HPE/hms-sls-charts
sources:
  - https://github.com/Cray-HPE/hms-sls
maintainers:
  - name: rsjostrand-hpe
dependencies:
  - name: cray-service
    version: "~11.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-postgresql
    version: "~1.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
appVersion: 2.9.0  # update pprof image version below as well
annotations:
  artifacthub.io/images: |-
    - name: cray-sls-pprof
      image: artifactory.algol60.net/csm-docker/stable/cray-sls-pprof:2.9.0
  artifacthub.io/license: MIT
