name: 'HMS Build Scripts'
description: 'Build environment and scripts for building HMS Helm charts'
inputs:
  target-branch:
      description: "Git repository branch to check against when determine charts that have changed"
      required: true
      default: "master"
  unstable-build-suffix:
      description: |
        The unstable build suffix is appended to the chart version for unstable builds.
        If the unstable build suffix is the empty string, then a stable build is performed.
      required: false
      default: ""

runs:
  using: 'docker'
  image: 'docker://artifactory.algol60.net/csm-docker/stable/hms-build-scripts:0.1.0'
  env:
      UNSTABLE_BUILD_SUFFIX: ${{ inputs.unstable-build-suffix }}
  args:
    - /bin/bash
    - -c
    - update-ct-config-with-chart-dirs.sh charts; build_changed_charts.sh ./charts ${{ inputs.target-branch }}