apiVersion: v2
name: "cray-hms-sls"
version: 2.0.0
description: "Kubernetes resources for cray-hms-sls"
home: https://github.com/Cray-HPE/hms-sls-charts
sources:
  - https://github.com/Cray-HPE/hms-sls
maintainers:
  - name: rsjostrand-hpe
dependencies:
  - name: cray-service
    version: "~7.0.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
annotations:
  artifacthub.io/license: MIT
  cray-hpe.github.io/allowed-csm-versions: ">= 1.2.0"  # CSM 1.2 and later
  cray-hpe.github.io/appversion-compatibility: "^1.11.0"  # App version 1.11.0 <= x.y.z < 2.0.0. Allow any later container image before a major bump
