name: Build and Publish Helm charts
on: [push]

jobs:
  build_and_release:
    name: Build and Publish Helm charts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Generate build suffix
      uses: Cray-HPE/hms-build-scripts/generate-build-suffix@master
      id: build-suffix

    - name: Build information
      shell: bash
      run: | 
        echo Build prefix: ${{ steps.build-suffix.outputs.build-suffix }}

    - name: Build changed charts
      uses: Cray-HPE/hms-build-scripts/build-changed-charts-action@master
      with:
        unstable-build-suffix: ${{ steps.build-suffix.outputs.build-suffix }}
    
    - name: Create Git tags for changed charts
      shell: bash
      run: | 
        for packaged_chart in .packaged/*; do
          chart_tag=$(basename "$packaged_chart" .tgz)
          echo "Chart tag: $chart_tag"
          git tag $chart_tag
        done

        git push origin --tags
      if: steps.build-suffix.outputs.build-suffix == null
    # - name: Publish Helm charts