name: Build and Publish Helm charts
on: [push]

jobs:
  build_and_release:
    name: Build and Publish Helm charts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Generate build suffix
      uses: Cray-HPE/hms-build-scripts/generate-build-suffix@master
      id: build-suffix
      # with:
      #   stable-branches-regex: feature/CASMHMS-5197-actions # This is a test

    - name: Build information
      shell: bash
      run: | 
        echo Stable Build:          ${{ steps.build-suffix.outputs.stable-build }};
        echo Unstable build prefix: ${{ steps.build-suffix.outputs.unstable-build-suffix }}
      if: steps.build-suffix.outputs.stable-build

    - name: Build changed charts
      uses: Cray-HPE/hms-build-scripts/build-changed-charts-action@master
      with:
        unstable-build-suffix: ${{ steps.build-suffix.outputs.unstable-build-suffix }}
    
    - name: Create Git tags for changed charts
      shell: bash
      run: | 
        echo ${{ steps.build-suffix.outputs.stable-build }}
      if: steps.build-suffix.outputs.stable-build
    # - name: Publish Helm charts