name: Build and Publish Helm charts
on: [push]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build changed charts
      uses: Cray-HPE/hms-build-scripts/build-changed-charts-action@master
      with:
        unstable-build-suffix: "foo"
    
    # - name: Create Git tags for changed charts
    # - name: Publish Helm charts