name: Build and Publish Helm charts
on: [push]

jobs:
  build_and_release:
    name: Build and Publish Helm charts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Generate build suffix
      uses: Cray-HPE/hms-build-scripts/generate-unstable-build-suffix@master
      id: build-suffix

    - name: Build changed charts
      uses: Cray-HPE/hms-build-scripts/build-changed-charts-action@master
      with:
        unstable-build-suffix: ${{ steps.build-suffix.outputs.unstable-build-suffix }}
    
    # - name: Create Git tags for changed charts
    # - name: Publish Helm charts