name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  lint-test-scan:
    # uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    # TODO Merge changes into Cray-HPE/.github
    uses: Cray-HPE/hms-sls-charts/.github/workflows/charts-lint-test-scan.other.yml@feature/CASMHMS-5197

    with:
      lint-charts: ${{ github.event_name == 'pull_request' }}
      ct-yaml: ct.yaml
      ct-yaml-post-script: ./lib/ct-test-customize.sh
      scan-image-snyk-args: "--severity-threshold=high"
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}